// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FadeTransition: typeof import('./src/pages/transition/components/FadeTransition.vue')['default']
    Foo: typeof import('./src/components/dummy/Foo.vue')['default']
    LearnVueIcon: typeof import('./src/components/LearnVueIcon.vue')['default']
    MyButton: typeof import('./src/components/atoms/MyButton.vue')['default']
    MyInput: typeof import('./src/components/writable-computed-v-model/MyInput.vue')['default']
    Parent: typeof import('./src/components/writable-computed-v-model/Parent.vue')['default']
    Playground: typeof import('./src/components/Playground.vue')['default']
    PropTypes: typeof import('./src/components/PropTypes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleText: typeof import('./src/components/dummy/SimpleText.vue')['default']
    SocialCard: typeof import('./src/components/SocialCard.vue')['default']
    Text: typeof import('./src/components/dummy/text.vue')['default']
  }
}
